### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by t-bast** [LLFourn/one-time-VES#1]
Thanks for this paper, this is a very interesting read and paves the way for a lot of cool layer-2 constructions, as well as academic review. 

I noticed a few typos, you tend to write "singing key" instead of "signing key" (also "singer/signer" and "sing/sign"). I think I'll always picture those singing keys in my head now, thanks for that :wink:.

I also noticed that you're using multiplicative notation for the tweaks instead of additive notation. Any particular reason for that? It surprised me a bit at first (probably because the groups I'm used to are always elliptic curve groups).

**Comment by LLFourn** [comment]
Not as bad as pubic keys!

Thanks very much for pointing out that typo. Fixed in https://github.com/LLFourn/one-time-VES/commit/208841053442ce65f737e62fa70bfd4412cab7c1

I used multiplicative notation just because that's what I'm used to.  I'm going to revise this paper in the coming months. Maybe I'll change it to additive. You're right that we are doing explicitly doing elliptic curve stuff here.
